apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "my-todo-chart.fullname" .}}

  labels:
    {{- include "my-todo-chart.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "my-todo-chart.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "my-todo-chart.selectorLabels" . | nindent 8}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
